"""
AI Research Module - Manual search links only
No external APIs or local LLMs required
"""

from datetime import datetime
from typing import Dict


def research_property_with_fallback(**kwargs) -> Dict:
    """Generate research with manual search links only"""
    
    address = kwargs.get('property_address', '')
    city = kwargs.get('city', '')
    
    encoded = (address or "").replace(' ', '+')
    
    return {
        "source": "manual",
        "research_summary": f"Research {address} using the search links below.",
        "full_research": "Use manual search links to research this property.",
        "key_findings": ["Use Google/MPAC links below for property research"],
        "google_search_url": f"https://www.google.com/search?q={encoded}+real+estate+{city}",
        "google_maps_url": f"https://www.google.com/maps/search/{encoded}",
        "mpac_search": "https://www.mpac.ca/en/property/assessment-search"
    }


def generate_obsidian_markdown(transaction: Dict, research: Dict) -> str:
    """Generate rich Obsidian markdown"""
    
    md = f"""# {transaction.get('property_address', 'Property')}

> **Deal Analysis** | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}
> **Source:** Manual Research Required

## Transaction Summary

| Field | Value |
|-------|-------|
| **Property** | {transaction.get('property_address', 'N/A')} |
| **Location** | {transaction.get('city', 'N/A')} |
| **Type** | {transaction.get('property_type', 'N/A')} |
| **Price** | ${transaction.get('sale_price', 0):,} |
| **Seller** | {transaction.get('seller_name', 'N/A')} |
| **Buyer** | {transaction.get('buyer_name', 'N/A')} |

## Research Links

- [Google Search]({research.get('google_search_url', f"https://www.google.com/search?q={(transaction.get('property_address') or '').replace(' ', '+')}")})
- [Google Maps]({research.get('google_maps_url', f"https://www.google.com/maps/search/{(transaction.get('property_address') or '').replace(' ', '+')}")})
- [MPAC Assessment](https://www.mpac.ca/en/property/assessment-search)

## Notes

```
{transaction.get('notes', '')}
```

#deal #{transaction.get('property_type', 'commercial').lower().replace(' ', '-')} #{transaction.get('city', 'ontario').lower().replace(' ', '-')} #hot-money

---
*Generated by BigDataClaw NERVE | Manual Research Required*
"""
    
    return md
