#!/usr/bin/env python3
"""
Create Obsidian notes for categorized companies (Investment, REITs, Private Equity)
"""

import csv
import os
from pathlib import Path
from datetime import datetime
from urllib.parse import quote_plus


VAULT_PATH = "/home/jamie/Desktop/Jamie's Personal Vault"
OUTPUT_BASE = f"{VAULT_PATH}/Companies_By_Category"


def generate_quick_links(name, location=None):
    """Generate Quick Links for a company"""
    base = "https://www.google.com/search"
    query = f"{name} {location}" if location else name
    
    return {
        'google': f"{base}?q={quote_plus(query)}",
        'linkedin': f"{base}?q={quote_plus(name + ' linkedin')}",
        'website': f"{base}?q={quote_plus(name + ' website')}",
        'news': f"{base}?q={quote_plus(name)}&tbm=nws",
        'loopnet': f"https://www.loopnet.com/search?q={quote_plus(name)}"
    }


def create_obsidian_note(company_data, category_folder):
    """Create Obsidian markdown note for a company"""
    # Extract data (using indices based on the CSV structure)
    company_id = company_data[0]
    name = company_data[1]
    address = company_data[2]
    city = company_data[3]
    province = company_data[4]
    postal = company_data[5]
    phone = company_data[6]
    
    # Get category info from the end of the row
    primary_cat = company_data[13] if len(company_data) > 13 else ''
    all_cats = company_data[14] if len(company_data) > 14 else ''
    
    location_str = ", ".join(filter(None, [city, province]))
    
    # Generate Quick Links
    links = generate_quick_links(name, location_str)
    
    # Create safe filename
    safe_name = name.replace(' ', '_').replace('/', '-').replace('\\', '')[:80]
    filename = f"{safe_name}.md"
    filepath = os.path.join(category_folder, filename)
    
    # Build content
    content = f"""---
type: company-profile
company: "{name}"
category: "{primary_cat.replace("'", "")}"
categories: "{all_cats}"
location: "{location_str}"
address: "{address}"
phone: "{phone}"
imported_date: {datetime.now().strftime('%Y-%m-%d')}
tags: [{primary_cat.replace("'", "").replace(' ', '-')}, company, "real-estate"]
---

# {name}

> 💼 **{primary_cat.replace("'", "").replace('_', ' ').title()}**

## 📍 Contact Information

"""
    
    if address:
        content += f"- **Address:** {address}\n"
    if location_str:
        content += f"- **Location:** {location_str}\n"
    if phone:
        content += f"- **Phone:** {phone}\n"
    
    content += f"""
## 🔍 Quick Links

| Platform | Link |
|----------|------|
| Google | [Search]({links['google']}) |
| LinkedIn | [Profile]({links['linkedin']}) |
| Website | [Find]({links['website']}) |
| News | [Search]({links['news']}) |
| LOOPNET | [Properties]({links['loopnet']}) |

## 📊 Categories

**Primary:** {primary_cat.replace("'", "")}

**All Categories:** {all_cats.replace('|', ', ')}

## 📝 Research Notes

- [ ] Research company background
- [ ] Check recent deals/transactions
- [ ] Review investment criteria
- [ ] Look for contact information

## 🎯 Outreach Status

| Date | Action | Response | Next Step |
|------|--------|----------|-----------|
| | | | |

---

*Generated by BigDataClaw Company Categorizer*  
*Date: {datetime.now().strftime('%Y-%m-%d')}*

#{primary_cat.replace("'", "").replace('_', '-')} #company #real-estate
"""
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    
    return filepath


def process_category(category_name, csv_file):
    """Process a category CSV and create Obsidian notes"""
    print(f"\n📁 Processing {category_name}...")
    
    category_folder = os.path.join(OUTPUT_BASE, category_name)
    Path(category_folder).mkdir(parents=True, exist_ok=True)
    
    count = 0
    with open(csv_file, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        header = next(reader)  # Skip header
        
        for row in reader:
            if len(row) < 15:
                continue
            
            try:
                create_obsidian_note(row, category_folder)
                count += 1
                
                if count % 100 == 0:
                    print(f"  ✓ Created {count} notes...")
            except Exception as e:
                print(f"  ❌ Error: {e}")
    
    print(f"  ✅ Total: {count} notes in {category_folder}")
    return count


def create_master_index(categories_processed):
    """Create master index file"""
    index_content = f"""---
type: company-index
title: "Companies by Category"
last_updated: {datetime.now().strftime('%Y-%m-%d')}
---

# 🏢 Companies by Category

Browse companies by their primary business category:

## 📊 Categories

"""
    
    emoji_map = {
        'BUILDERS': '🏗️',
        'INVESTMENT': '💰',
        'REITS': '🏢',
        'PRIVATE_EQUITY': '📈',
        'PENSION_FUNDS': '🎓',
        'FAMILY_OFFICES': '👨‍👩‍👧‍👦',
        'INSURANCE': '🛡️',
        'LENDERS': '🏦'
    }
    
    for cat_name, count in categories_processed.items():
        emoji = emoji_map.get(cat_name, '🏢')
        folder_name = cat_name
        index_content += f"| {emoji} [[{folder_name}/_Index\|{cat_name.replace('_', ' ').title()}]] | {count:,} companies |\n"
    
    index_content += f"""

## 🔍 Quick Links

| Resource | Link |
|----------|------|
| All Companies | [[_All_Companies\|View All]] |
| Recent Updates | [[_Recent\|Recently Updated]] |

---

*Generated: {datetime.now().strftime('%Y-%m-%d')}*
"""
    
    index_path = os.path.join(OUTPUT_BASE, "_Index.md")
    with open(index_path, 'w', encoding='utf-8') as f:
        f.write(index_content)
    
    print(f"\n  📝 Master index: {index_path}")


if __name__ == "__main__":
    print("="*70)
    print("🏢 CREATING OBSIDIAN NOTES BY CATEGORY")
    print("="*70)
    
    base_dir = "/home/jamie/Desktop/Jamie's Personal Vault/bigdataclaw/COMPANIES_BY_CATEGORY"
    
    categories = {
        'INVESTMENT': f'{base_dir}/INVESTMENT.csv',
        'REITS': f'{base_dir}/REITS.csv',
        'PRIVATE_EQUITY': f'{base_dir}/PRIVATE_EQUITY.csv',
        'PENSION_FUNDS': f'{base_dir}/PENSION_FUNDS.csv',
        'FAMILY_OFFICES': f'{base_dir}/FAMILY_OFFICES.csv',
        'INSURANCE': f'{base_dir}/INSURANCE.csv',
    }
    
    processed = {}
    
    for cat_name, csv_file in categories.items():
        if os.path.exists(csv_file):
            count = process_category(cat_name, csv_file)
            processed[cat_name] = count
        else:
            print(f"  ⚠️  File not found: {csv_file}")
    
    # Create master index
    create_master_index(processed)
    
    print("\n" + "="*70)
    print("✅ CATEGORY NOTES CREATED!")
    print("="*70)
    print(f"\nLocation: {OUTPUT_BASE}/")
    print("\nCategories created:")
    for cat, count in processed.items():
        print(f"  • {cat}: {count:,} notes")
