# Obsidian Bridge for Deal Generator
# Place this in your OpenClaw workspace

OBSIDIAN_HOST=${OBSIDIAN_HOST:-"localhost"}
OBSIDIAN_PORT=${OBSIDIAN_PORT:-"27123"}
OBSIDIAN_API_KEY=${OBSIDIAN_API_KEY:-""}

# Test connection to Obsidian
test_obsidian_connection() {
    echo "Testing Obsidian connection..."
    
    response=$(curl -s -o /dev/null -w "%{http_code}" \
        "http://${OBSIDIAN_HOST}:${OBSIDIAN_PORT}/vault/" \
        -H "Authorization: Bearer ${OBSIDIAN_API_KEY}")
    
    if [ "$response" = "200" ]; then
        echo "✅ Connected to Obsidian successfully!"
        return 0
    else
        echo "❌ Connection failed (HTTP $response)"
        echo "Make sure:"
        echo "  1. Obsidian is running"
        echo "  2. Local REST API plugin is enabled"
        echo "  3. API key is correct"
        echo "  4. IP address is correct"
        return 1
    fi
}

# Create a note in Obsidian
create_note() {
    local path="$1"
    local content="$2"
    
    curl -X PUT \
        "http://${OBSIDIAN_HOST}:${OBSIDIAN_PORT}/vault/${path}" \
        -H "Authorization: Bearer ${OBSIDIAN_API_KEY}" \
        -H "Content-Type: text/markdown" \
        -d "$content"
    
    echo "✅ Created: $path"
}

# Read a note from Obsidian
read_note() {
    local path="$1"
    
    curl -s \
        "http://${OBSIDIAN_HOST}:${OBSIDIAN_PORT}/vault/${path}" \
        -H "Authorization: Bearer ${OBSIDIAN_API_KEY}"
}

# Search Obsidian vault
search_vault() {
    local query="$1"
    
    curl -s -X POST \
        "http://${OBSIDIAN_HOST}:${OBSIDIAN_PORT}/search/" \
        -H "Authorization: Bearer ${OBSIDIAN_API_KEY}" \
        -H "Content-Type: application/json" \
        -d "{\"query\": \"$query\"}"
}

# Create daily activity note
create_daily_note() {
    local date=$(date +%Y-%m-%d)
    local content="# Daily Activity - $date

## 🎯 Priority Actions
- [ ] 
- [ ] 
- [ ] 

## 📞 Calls Made
| Time | Contact | Result | Next Action |
|------|---------|--------|-------------|
| | | | |

## 🔥 Hot Money Updates

## 📧 Emails Sent

## 📝 Notes

---
*Generated by Kimi Claw AI*"
    
    create_note "Daily/$date.md" "$content"
}

# Create buyer profile
create_buyer_profile() {
    local name="$1"
    local company="$2"
    local phone="$3"
    local deal="$4"
    local match_score="$5"
    
    local content="# $name

## Contact Info
- **Company:** $company
- **Phone:** $phone
- **Email:** 
- **LinkedIn:** 

## Deal History
- **Recent Deal:** $deal
- **Asset Class:** 
- **Location:** 

## Match Analysis
- **Score:** $match_score%
- **Status:** Hot
- **Priority:** Call Today

## Notes

## Communication Log
| Date | Type | Notes |
|------|------|-------|
| | | |

---
#buyer #hot-money"
    
    create_note "Buyers/Hot_Money/$name.md" "$content"
}

# Export function for sourcing
export_obsidian_config() {
    echo "export OBSIDIAN_HOST=\"$OBSIDIAN_HOST\""
    echo "export OBSIDIAN_PORT=\"$OBSIDIAN_PORT\""
    echo "export OBSIDIAN_API_KEY=\"$OBSIDIAN_API_KEY\""
}

# Menu
show_menu() {
    echo ""
    echo "🔌 OBSIDIAN BRIDGE - Deal Generator"
    echo "===================================="
    echo ""
    echo "1. Test connection"
    echo "2. Create daily note"
    echo "3. Create buyer profile"
    echo "4. Search vault"
    echo "5. Export configuration"
    echo "q. Quit"
    echo ""
}

# Main
if [ -z "$OBSIDIAN_API_KEY" ]; then
    echo "⚠️  Please set OBSIDIAN_API_KEY environment variable"
    echo "   Example: export OBSIDIAN_API_KEY='your-key-here'"
    exit 1
fi

# Run menu if called directly
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    while true; do
        show_menu
        read -p "Select option: " choice
        
        case $choice in
            1) test_obsidian_connection ;;
            2) create_daily_note ;;
            3) 
                read -p "Buyer name: " name
                read -p "Company: " company
                read -p "Phone: " phone
                read -p "Recent deal: " deal
                read -p "Match score: " score
                create_buyer_profile "$name" "$company" "$phone" "$deal" "$score"
                ;;
            4)
                read -p "Search query: " query
                search_vault "$query"
                ;;
            5) export_obsidian_config ;;
            q) exit 0 ;;
            *) echo "Invalid option" ;;
        esac
    done
fi